[plugin]
summary = 'workflow审批流'
version = '0.1.0'
description = '基于 SnakerFlow 扩展的后端审批流引擎，提供流程定义管理、任务流转控制与实例状态维护功能'
author = 'shj366'
tags = ['task', 'notification', 'other']
database = ['mysql', ]

[app]
router = ['v1']
