[plugin]
summary = 'jeeflow 工作流审批流'
version = '1.8.28'
description = '基于 jeeflow-python 与 jeeflow-ui 的统一门面工作流插件'
author = 'mldong / Flzk'
tags = ['task', 'notification', 'other']
database = ['mysql', ]

[app]
router = ['v1']
